server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: auth-server
  security:
    oauth2:
      client:
        registration:
          google-client:
            provider: google
            client-id: ${OKTA_CLIENT_ID:fake}
            client-secret: ${OKTA_CLIENT_SECRET:fake}
            scope:
              - openid
              - profile
              - email
          okta-client:
            provider: okta
            client-id: ${OKTA_CLIENT_ID:fake}
            client-secret: ${OKTA_CLIENT_SECRET:fake}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: ${okta.base-url}/oauth2/v1/authorize
            token-uri: ${okta.base-url}/oauth2/v1/token
            user-info-uri: ${okta.base-url}/oauth2/v1/userinfo
            jwk-set-uri: ${okta.base-url}/oauth2/v1/keys
            user-name-attribute: sub
          okta:
            authorization-uri: ${okta.base-url}/oauth2/v1/authorize
            token-uri: ${okta.base-url}/oauth2/v1/token
            user-info-uri: ${okta.base-url}/oauth2/v1/userinfo
            jwk-set-uri: ${okta.base-url}/oauth2/v1/keys
            user-name-attribute: sub
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
          pkce-client:
            registration:
              client-id: "pkce-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:7000/pkce-demo.html"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
            require-proof-key: true
